configVersion: 1.0.0
componentName: BASIC CONFIGURATION
coreVersion: 5.8.3
device: ATSAME54P20A
library: []
dependency:
- dependencyPackage: class com.microchip.mcc.harmony.HarmonyGroupModule
  name: BASIC CONFIGURATION
  type: module
  version: ''
- dependencyPackage: ''
  name: CMSIS_5
  type: package
  version: 5.9.0
- dependencyPackage: ''
  name: FreeRTOS-Kernel
  type: package
  version: V11.2.0
- dependencyPackage: ''
  name: core
  type: package
  version: v3.16.0
- dependencyPackage: ''
  name: core
  type: package
  version: v3.16.0
- dependencyPackage: ''
  name: crypto
  type: package
  version: v3.8.2
- dependencyPackage: ''
  name: csp
  type: package
  version: v3.24.0
- dependencyPackage: ''
  name: csp
  type: package
  version: v3.24.0
- dependencyPackage: ''
  name: net
  type: package
  version: v3.14.4
- dependencyPackage: ''
  name: net_10base_t1s
  type: package
  version: v1.4.1
- dependencyPackage: ''
  name: net_10base_t1s
  type: package
  version: v1.4.1
- dependencyPackage: ''
  name: wolfssl
  type: package
  version: v5.4.0
customDataClassName: com.microchip.utils_mh3.utils.persistence.CustomModuleData
data:
  attachments:
    children:
    - children:
      - attributes:
          id: Core_SysConsole_Dependency
          namespace: tcpipStack
          targetAttachmentID: TCP/IP STACK:tcpipStack:Core_SysConsole_Dependency
          targetComponentID: TCP/IP STACK
        type: Attachment
      type: Attachments
    type: BASIC CONFIGURATION
  elementPosition: {}
  symbols: {}
  userData: {}
